services:
  redis:
    container_name: redis
    image: public.ecr.aws/docker/library/redis:alpine
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  # express_server:
  #   container_name: express_server
  #   image: neopan718/cns-express-server:1.0
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  socket_server:
    container_name: socket_server
    image: neopan718/cns-socket-server:1.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
